version: '3'

services:
  discord-music-bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: discord-music-bot
    restart: unless-stopped
    volumes:
      - ../data:/app/data
    env_file:
      - ../.env
