version: '3'

services:
  discord-music-bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: discord-music-bot
    restart: unless-stopped
    volumes:
      - ../data:/app/data
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - YOUTUBE_CLIENT_ID=${YOUTUBE_CLIENT_ID}
      - YOUTUBE_CLIENT_SECRET=${YOUTUBE_CLIENT_SECRET}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - SSL_VERIFY=${SSL_VERIFY:-False}
      - TOKEN_PICKLE_PATH=/app/data/token.pickle